---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ersatztv.fullname" . }}-config

  labels:
    {{- include "ersatztv.labels" . | nindent 4 }}
    volume: config
spec: {{ toYaml .Values.persistence.volumeClaimSpec | nindent 2 }}