---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ersatztv.fullname" . }}-data
  labels:
    volume: data
spec:
  storageClassName: ""
  selector:
    matchLabels:
      volume: data
  accessModes: {{ toYaml .Values.volume.volumeSpec.accessModes | nindent 4 }}
  resources:
    requests: {{ toYaml .Values.volume.volumeSpec.capacity | nindent 6 }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "ersatztv.fullname" . }}-data
  labels:
    volume: data
spec: {{ toYaml .Values.volume.volumeSpec | nindent 2 }}